name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@master
      - name: Building Docker Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chuwoo/fsr
          username: '${{ secrets. }}'
          password: '${{ secrets. }}'
      
